### ISSUE TITLE
imagenet japanese class names

### ISSUE THREAD

**Issue by rom1504** [rinnakk/japanese-clip#2]
Hi,
Awesome repo

Could you please share the imagenet class names / prompt you used for zero shot evaluation?

I'm trying to build a good evaluation framework for clip (https://github.com/LAION-AI/CLIP_benchmark) and having these class names in other languages would be valuable

Thanks for your help!

**Comment by mkshing** [comment]
Hi,
Thank you for your interest in our work. 
We used the following file as the imagenet class names and converted them to "{}の写真" as prompts. 
https://gist.github.com/PonDad/4dcb4b242b9358e524b4ddecbee385e9

**Comment by mkshing** [comment]
@rom1504 Hi, I have an update for this. We released [v0.2.0](https://github.com/rinnakk/japanese-clip#july-2022) and the imagenet japanese prompt templates were different from the previous one v0.1.0. The new prompt templates were cleaned up for Japanese lang based on the [OpenAI 80 templates](https://github.com/openai/CLIP/blob/main/notebooks/Prompt_Engineering_for_ImageNet.ipynb). For example, "a photo of the {}" and "a photo of a {}" are identical in Japanese. 
https://github.com/rinnakk/japanese-clip/blob/master/src/japanese_clip/utils/imagenet_zeroshot_data.py#L1003
